# Generated by Django 2.1.3 on 2018-12-08 01:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ontask_oauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ontaskoauthusertokens',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oauth2_token', to=settings.AUTH_USER_MODEL),
        ),
    ]
