# Generated by Django 2.1.3 on 2018-12-08 02:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontask_oauth', '0003_auto_20181208_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ontaskoauthusertokens',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oauth2_token', to=settings.AUTH_USER_MODEL),
        ),
    ]
