# Generated by Django 2.2.3 on 2019-08-02 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='oauthusertoken',
            table='oauth_user_token',
        ),
    ]
