# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0004_auto_20171122_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='is_out',
            field=models.BooleanField(default=True, verbose_name='Action is provide information'),
        ),
    ]
