# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-30 04:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0023_set_content_and_columns'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='_content',
            new_name='content',
        ),
    ]
