# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-23 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0026_auto_20180723_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='description_text',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='action',
            name='name',
            field=models.CharField(max_length=256, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='description_text',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='name',
            field=models.CharField(max_length=256, verbose_name='name'),
        ),
    ]
