# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-21 05:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0036_action_last_executed_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='last_executed',
        ),
    ]
