# Generated by Django 2.1.3 on 2018-12-06 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0040_auto_20181123_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='action_type',
            field=models.CharField(choices=[('personalized_text', 'Personalized text'), ('personalized_canvas_email', 'Personalized Canvas Email'), ('survey', 'Survey'), ('personalized_json', 'Personalized JSON'), ('todo_list', 'TODO List')], default='personalized_text', max_length=64),
        ),
    ]
