# Generated by Django 2.1.7 on 2019-03-23 03:06

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0058_remove_action_nrows_all_false'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='rows_all_false',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True),
        ),
    ]
