# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-24 23:00
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_log_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='payload',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True, verbose_name='payload'),
        ),
    ]
