# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-16 08:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_auto_20171216_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledaction',
            name='user',
        ),
        migrations.RemoveField(
            model_name='scheduledaction',
            name='workflow',
        ),
        migrations.DeleteModel(
            name='ScheduledAction',
        ),
    ]
