# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-19 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0009_auto_20171218_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledemailaction',
            name='message',
            field=models.TextField(blank=True, verbose_name='Execution message'),
        ),
    ]
