# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-17 06:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0011_scheduledemailaction_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledemailaction',
            name='add_column',
        ),
    ]
