# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-18 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0008_remove_scheduledemailaction_workflow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledemailaction',
            name='status',
            field=models.IntegerField(choices=[(0, 'pending'), (1, 'running'), (2, 'done'), (3, 'done_error')], verbose_name='Execution Status'),
        ),
    ]
