# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-26 05:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0021_auto_20180826_1458'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScheduledEmailAction',
            new_name='ScheduledAction',
        ),
    ]
