# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-26 05:35
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0022_auto_20180826_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledaction',
            name='payload',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True, verbose_name='payload'),
        ),
        migrations.AlterField(
            model_name='scheduledaction',
            name='exclude_values',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True, verbose_name='exclude values'),
        ),
    ]
