# Generated by Django 2.2.3 on 2019-08-02 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0025_auto_20180826_1830_squashed_0035_remove_scheduledaction_deleted'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='scheduledaction',
            table='scheduled_action',
        ),
    ]
