# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-28 10:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0029_auto_20180828_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledaction',
            name='type',
        ),
    ]
