# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-22 07:04
from __future__ import unicode_literals

from django.db import migrations

from dataops.formula_evaluation import get_variables


def add_columns_to_conditions(apps, schema_editor):
    """
    Traverse all conditions in all actions of all workflows to add the many
    to many relation to the columns.

    :param apps:
    :param schema_editor:
    :return:
    """
    if schema_editor.connection.alias != 'default':
        return

    Workflow = apps.get_model('workflow', 'Workflow')
    for workflow in Workflow.objects.all():
        for action in workflow.actions.all():
            for condition in action.conditions.all():
                # Get variable names in the formula
                col_names = get_variables(condition.formula)

                # Add the corresponding columns to the condition
                condition.columns.set(
                    workflow.columns.filter(name__in=col_names)
                )

class Migration(migrations.Migration):

    dependencies = [
        ('action', '0013_condition_columns'),
    ]

    operations = [
        migrations.RunPython(add_columns_to_conditions),
    ]
