# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-21 07:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0021_action_shuffle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='content',
            new_name='_content',
        ),
    ]
