# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-23 00:41
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0025_auto_20180722_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='formula',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True, verbose_name='formula'),
        ),
    ]
