# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-14 03:57
from __future__ import unicode_literals

from django.db import migrations, models


def change_action_type(apps, schema_editor):
    """
    Traverse all actions to change is_out = True by personal_tex
    and is_out = False by survey.

    :param apps:
    :param schema_editor:
    :return:
    """
    if schema_editor.connection.alias != 'default':
        return

    Action = apps.get_model('action', 'Action')
    for item in Action.objects.all():
        if item.is_out:
            item.action_type = 'personal_text'
        else:
            item.action_type = 'survey'
        item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0029_auto_20180814_1327'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='action',
        #     name='action_type',
        #     field=models.CharField(choices=[('personal_text', 'Personalized text'), ('json', 'Personalized JSON'), ('survey', 'Survey'), ('todolist', 'TODO List')], default='personal_text', max_length=64),
        # ),
        migrations.RunPython(change_action_type),
        migrations.RemoveField(
            model_name='action',
            name='is_out',
        ),
    ]
