# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-18 08:05
from __future__ import unicode_literals

from django.db import migrations


def change_action_type(apps, schema_editor):
    """
    Traverse all actions to change json by personalized_json

    :param apps:
    :param schema_editor:
    :return:
    """
    if schema_editor.connection.alias != 'default':
        return

    Action = apps.get_model('action', 'Action')
    for item in Action.objects.all():
        if item.action_type == 'personal_text':
            item.action_type = 'personalized_text'
            item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0030_auto_20180818_1714'),
    ]

    operations = [
        migrations.RunPython(change_action_type),
    ]
