# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-26 05:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0037_remove_action_last_executed'),
    ]

    operations = [
    ]
