# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-23 04:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0039_merge_20180905_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='action_type',
            field=models.CharField(choices=[('personalized_text', 'Personalized text'), ('personalized_json', 'Personalized JSON'), ('personalized_canvas_email', 'Personalized Canvas Email'), ('survey', 'Survey'), ('todo_list', 'TODO List')], default='personalized_text', max_length=64),
        ),
    ]
