# Generated by Django 2.1.3 on 2018-12-12 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0043_auto_20181212_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='name',
            field=models.CharField(blank=True, max_length=256, verbose_name='name'),
        ),
    ]
