# Generated by Django 2.1.7 on 2019-02-28 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0046_auto_20190228_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='columnconditionpair',
            name='action',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='columns_TMP', to='action.Action'),
            preserve_default=False,
        ),
    ]
