# Generated by Django 2.2 on 2019-04-30 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0059_auto_20190323_1336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='content',
            new_name='text_content',
        ),
        migrations.AlterField(
            model_name='action',
            name='name',
            field=models.CharField(max_length=512, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='name',
            field=models.CharField(blank=True, max_length=512, verbose_name='name'),
        ),
    ]
