# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-13 10:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workflow', '0002_auto_20171110_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='shared',
            field=models.ManyToManyField(related_name='shared_workflows', to=settings.AUTH_USER_MODEL),
        ),
    ]
