# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-28 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0018_auto_20180428_1425'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='column',
            options={'ordering': ('-is_key', 'position')},
        ),
        migrations.AddField(
            model_name='column',
            name='position',
            field=models.IntegerField(default=0, verbose_name='Column position'),
        ),
    ]
