# Generated by Django 2.2 on 2019-04-18 06:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0028_auto_20190418_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='shared',
            field=models.ManyToManyField(related_name='workflows_shared', to=settings.AUTH_USER_MODEL),
        ),
    ]
