# Generated by Django 2.2.1 on 2019-05-24 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0028_auto_20190418_1550_squashed_0035_auto_20190430_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='session_key',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
