# Generated by Django 2.2.3 on 2019-08-02 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0030_workflow_star'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='column',
            table='column',
        ),
        migrations.AlterModelTable(
            name='workflow',
            table='workflow',
        ),
    ]
