# Generated by Django 2.2.2 on 2019-06-30 02:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ontask', '0002_auto_20190521_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthUserToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_name', models.CharField(max_length=2048)),
                ('access_token', models.CharField(max_length=2048)),
                ('refresh_token', models.CharField(blank=True, max_length=2048)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('valid_until', models.DateTimeField(default=None, verbose_name='Token valid until')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'instance_name')},
            },
        ),
    ]
