# Generated by Django 2.2.1 on 2019-05-24 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('ontask', '0001_dataops_initial'), ('ontask', '0002_auto_20171120_1703'), ('ontask', '0003_rowview_filter'), ('ontask', '0004_auto_20171124_0604'), ('ontask', '0005_auto_20171207_1835'), ('ontask', '0006_pluginregistry'), ('ontask', '0007_auto_20180523_2004'), ('ontask', '0008_pluginregistry_is_verified'), ('ontask', '0009_pluginregistry_diagnostics'), ('ontask', '0010_remove_pluginregistry_diagnostics'), ('ontask', '0011_auto_20180526_1430'), ('ontask', '0012_sqlconnection'), ('ontask', '0013_auto_20180530_0752'), ('ontask', '0014_auto_20180530_0754'), ('ontask', '0015_auto_20180530_0914'), ('ontask', '0016_sqlconnection_db table name'), ('ontask', '0017_sqlconnection_connection driver'), ('ontask', '0018_auto_20180530_1217'), ('ontask', '0019_auto_20180530_1220'), ('ontask', '0020_auto_20180530_1314'), ('ontask', '0021_auto_20180530_1316'), ('ontask', '0022_auto_20190106_0051'), ('ontask', '0023_pluginregistry_is_model'), ('ontask', '0024_auto_20190430_1922'), ('ontask', '0025_auto_20190510_1928')]

    initial = True

    dependencies = [
        ('ontask', '0003_workflow_shared'),
    ]

    operations = [
        migrations.CreateModel(
            name='SQLConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2048, unique=True, verbose_name='Name')),
                ('description_txt', models.CharField(blank=True, default='', max_length=2048, verbose_name='Description')),
                ('conn_type', models.CharField(help_text='Postgresql, Mysql, etc.', max_length=2048, verbose_name='Type')),
                ('db_user', models.CharField(blank=True, default='', max_length=2048, verbose_name='User')),
                ('db_password', models.BooleanField(default=False, verbose_name='Requires password?')),
                ('db_host', models.CharField(blank=True, default='', max_length=2048, verbose_name='Host')),
                ('db_port', models.IntegerField(blank=True, null=True, verbose_name='Port')),
                ('db_name', models.CharField(default='', max_length=2048, verbose_name='DB name')),
                ('db_table', models.CharField(default='', max_length=2048, verbose_name='Table')),
                ('conn_driver', models.CharField(blank=True, default='', help_text='Driver implementing the DBAPI', max_length=2048, verbose_name='Driver')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PluginRegistry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=2048, unique=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256)),
                ('description_txt', models.CharField(blank=True, default='', max_length=65536)),
                ('executed', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Last verified')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Ready to run')),
                ('is_model', models.BooleanField(default=False, verbose_name='Plugin is a model')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
