# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-01 10:33
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='Column name')),
                ('data_type', models.CharField(choices=[('string', 'string'), ('integer', 'integer'), ('double', 'double'), ('boolean', 'boolean'), ('datetime', 'datetime')], max_length=512, verbose_name='Type of data to store in the column')),
                ('is_key', models.BooleanField(default=False, verbose_name='Has unique values per row')),
                ('categories', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True, verbose_name='Comma separated list of allowed values')),
            ],
            options={
                'ordering': ('-is_key', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('description_text', models.CharField(blank=True, default='', max_length=2048)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('nrows', models.IntegerField(blank=True, default=0, verbose_name='Number of rows')),
                ('ncols', models.IntegerField(blank=True, default=0, verbose_name='Number of columns')),
                ('attributes', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('query_builder_ops', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('data_frame_table_name', models.CharField(blank=True, default='', max_length=1024)),
                ('session_key', models.CharField(blank=True, default='', max_length=40)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='column',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='ontask.Workflow'),
        ),
        migrations.AlterUniqueTogether(
            name='workflow',
            unique_together=set([('user', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='column',
            unique_together=set([('name', 'workflow')]),
        ),
    ]
