# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-19 08:10
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0003_workflow_shared'),
    ]

    operations = [
        migrations.CreateModel(
            name='RowView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('description_text', models.CharField(blank=True, default='', max_length=2048)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('columns', models.ManyToManyField(related_name='rowview', to='ontask.Column')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rowview', to='ontask.Workflow')),
            ],
        ),
    ]
