# Generated by Django 2.2.4 on 2019-08-20 11:29

from django.db import connection as con, migrations


class Migration(migrations.Migration):
    dependencies = [
        ('ontask', '0001_oauth_initial'),
    ]

    __table_name_pairs = [
        ('action_action', 'ontask_action'),
        ('action_actioncolumnconditiontuple',
         'ontask_actioncolumnconditiontuple'),
        ('workflow_column', 'ontask_column'),
        ('action_condition', 'ontask_condition'),
        ('logs_log', 'ontask_log'),
        ('oauth_oauthusertoken', 'ontask_oauthusertoken'),
        ('core_ontaskuser', 'ontask_ontaskuser'),
        ('dataops_plugin', 'ontask_plugin'),
        ('profiles_profile', 'ontask_profile'),
        ('scheduler_scheduledaction', 'ontask_scheduledaction'),
        ('dataops_sqlconnection', 'ontask_sqlconnection'),
        ('table_view', 'ontask_view'),
        ('workflow_workflow', 'ontask_workflow'),
        ('action_condition_columns', 'ontask_condition_columns'),
        ('table_view_columns', 'ontask_view_columns'),
        ('workflow_workflow_shared', 'ontask_workflow_shared'),
        ('workflow_workflow_lusers', 'ontask_workflow_lusers'),
        ('workflow_workflow_star', 'ontask_workflow_star'),
    ]
    __sql_query = 'ALTER TABLE {0} RENAME TO {1}'

    operations = []
    with con.cursor() as cursor:
        table_names = [
            citem.name for citem in con.introspection.get_table_list(cursor)]
        for final_name, start_name in __table_name_pairs:
            if start_name in table_names and final_name in table_names:
                operations.append(
                    migrations.RunSQL(
                        'DROP TABLE IF EXISTS {0} CASCADE'.format(start_name)))
            if final_name in table_names:
                operations.append(
                    migrations.RunSQL(
                        __sql_query.format(final_name, start_name)))

    operations += [
        migrations.AlterModelTable(
            name='action',
            table='action_action',
        ),
        migrations.AlterModelTable(
            name='actioncolumnconditiontuple',
            table='action_actioncolumnconditiontuple',
        ),
        migrations.AlterModelTable(
            name='column',
            table='workflow_column',
        ),
        migrations.AlterModelTable(
            name='condition',
            table='action_condition',
        ),
        migrations.AlterModelTable(
            name='log',
            table='logs_log',
        ),
        migrations.AlterModelTable(
            name='oauthusertoken',
            table='oauth_oauthusertoken',
        ),
        migrations.AlterModelTable(
            name='ontaskuser',
            table='core_ontaskuser',
        ),
        migrations.AlterModelTable(
            name='plugin',
            table='dataops_plugin',
        ),
        migrations.AlterModelTable(
            name='profile',
            table='profiles_profile',
        ),
        migrations.AlterModelTable(
            name='scheduledaction',
            table='scheduler_scheduledaction',
        ),
        migrations.AlterModelTable(
            name='sqlconnection',
            table='dataops_sqlconnection',
        ),
        migrations.AlterModelTable(
            name='view',
            table='table_view',
        ),
        migrations.AlterModelTable(
            name='workflow',
            table='workflow_workflow',
        ),
    ]
