# Generated by Django 2.2 on 2019-05-21 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0001_squashed_0005_auto_20190419_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Short Bio'),
        ),
    ]
