# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-20 06:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_workflow_shared'),
        ('ontask', '0001_dataops_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rowview',
            options={'ordering': ('name',)},
        ),
        migrations.AlterUniqueTogether(
            name='rowview',
            unique_together=set([('name', 'workflow')]),
        ),
    ]
