# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-16 04:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0001_table_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='view',
            old_name='filter',
            new_name='formula',
        ),
    ]
