# Generated by Django 2.2.7 on 2019-12-01 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0001_oauth_initial_squashed_0065_auto_20191201_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubriccell',
            name='loa_position',
            field=models.IntegerField(verbose_name='level of attainment'),
        ),
    ]
