# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-30 02:54
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0001_logs_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='workflow',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.Workflow'),
        ),
    ]
