# Generated by Django 2.2.4 on 2019-08-20 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0001_oauth_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='action',
            table='action_action',
        ),
        migrations.AlterModelTable(
            name='actioncolumnconditiontuple',
            table='action_actioncolumnconditiontuple',
        ),
        migrations.AlterModelTable(
            name='column',
            table='workflow_column',
        ),
        migrations.AlterModelTable(
            name='condition',
            table='action_condition',
        ),
        migrations.AlterModelTable(
            name='log',
            table='logs_log',
        ),
        migrations.AlterModelTable(
            name='oauthusertoken',
            table='oauth_oauthusertoken',
        ),
        migrations.AlterModelTable(
            name='ontaskuser',
            table='core_ontaskuser',
        ),
        migrations.AlterModelTable(
            name='plugin',
            table='dataops_plugin',
        ),
        migrations.AlterModelTable(
            name='profile',
            table='profiles_profile',
        ),
        migrations.AlterModelTable(
            name='scheduledaction',
            table='scheduler_scheduledaction',
        ),
        migrations.AlterModelTable(
            name='sqlconnection',
            table='dataops_sqlconnection',
        ),
        migrations.AlterModelTable(
            name='view',
            table='table_view',
        ),
        migrations.AlterModelTable(
            name='workflow',
            table='workflow_workflow',
        ),
    ]
