# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-22 04:40
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0002_auto_20171120_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='rowview',
            name='filter',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
    ]
