# Generated by Django 2.2.4 on 2019-08-19 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0002_auto_20190521_1710'),
        ('ontask', '0001_squashed_0005_auto_20190419_0738'),
    ]

    operations = [
#        migrations.AlterModelTable(
#            name='profile',
#            table='profiles_profile',
#        ),
    ]
