# Generated by Django 2.2 on 2019-04-18 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0002_auto_20190418_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ontaskuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ontask_info', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
