# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-16 10:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0013_auto_20171209_0809'),
        ('ontask', '0002_auto_20180116_1510'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='view',
            options={'ordering': ('name',)},
        ),
        migrations.AlterUniqueTogether(
            name='view',
            unique_together=set([('name', 'workflow')]),
        ),
    ]
