# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-16 04:43
from __future__ import unicode_literals

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0002_auto_20171111_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='condition',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
