# Generated by Django 2.2.8 on 2019-12-06 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0011_auto_20190508_0153'),
        ('ontask', '0003_auto_20191204_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledoperation',
            name='frequency',
            field=models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='frequency'),
        ),
        migrations.AddField(
            model_name='scheduledoperation',
            name='periodic_task',
            field=models.ForeignKey(null=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_op', to='django_celery_beat.PeriodicTask'),
            preserve_default=False,
        ),
    ]
