# Generated by Django 2.2.2 on 2019-06-08 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0003_auto_20190608_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugin',
            name='is_enabled',
            field=models.BooleanField(default=False, verbose_name='Enabled'),
        ),
    ]
