# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-22 04:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0003_auto_20171116_1543'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='condition',
            options={'ordering': ('created',)},
        ),
    ]
