# Generated by Django 2.2.4 on 2019-08-20 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0003_auto_20190820_0713'),
    ]

    operations = [
    ]
