# Generated by Django 2.2.4 on 2019-08-24 06:02

from django.db import connection as con, migrations
from psycopg2 import sql


def remove_old_migration_refs(apps, schema_editor):
    __sql_delete_migration_ref = 'DELETE FROM django_migrations WHERE app={0}'

    old_apps = [
        'action', 'core', 'dataops', 'logs', 'oauth', 'ontask_oauth',
        'profiles', 'scheduler', 'table', 'workflow']

    with con.cursor() as cursor:
        for app_name in old_apps:
            cursor.execute(
                sql.SQL(__sql_delete_migration_ref).format(
                    sql.Literal(app_name)))


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0003_transfer_siteprefs'),
    ]

    operations = [
        migrations.RunPython(code=remove_old_migration_refs),
    ]
