# Generated by Django 2.2.8 on 2019-12-07 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0005_auto_20191207_1326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduledoperation',
            old_name='task id',
            new_name='task_uuid',
        ),
    ]
