# Generated by Django 2.2.4 on 2019-08-24 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0005_auto_20190824_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='action_type',
            field=models.CharField(choices=[('personalized_text', 'Personalized text'), ('personalized_canvas_email', 'Personalized Canvas Email'), ('survey', 'Survey'), ('personalized_json', 'Personalized JSON'), ('send_list', 'Send List'), ('todo_list', 'TODO List')], default='personalized_text', max_length=64),
        ),
    ]
