# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 11:21
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0006_action_columns'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='action',
            name='filter',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='Preselect rows satisfying this condition', null=True),
        ),
    ]
