# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-23 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0006_pluginregistry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pluginregistry',
            options={'ordering': ('name',)},
        ),
        migrations.RemoveField(
            model_name='pluginregistry',
            name='num_column_input_from',
        ),
        migrations.RemoveField(
            model_name='pluginregistry',
            name='num_column_input_to',
        ),
        migrations.AddField(
            model_name='pluginregistry',
            name='executed',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Last execution'),
        ),
    ]
