# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-09 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0007_auto_20171206_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='active_from',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Action available from'),
        ),
        migrations.AddField(
            model_name='action',
            name='active_to',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Action available until'),
        ),
    ]
