# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-26 02:37
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0008_pluginregistry_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='pluginregistry',
            name='diagnostics',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True, verbose_name='Plugin diagnostics'),
        ),
    ]
