# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-28 04:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0008_auto_20171209_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
