# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-26 03:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0009_pluginregistry_diagnostics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pluginregistry',
            name='diagnostics',
        ),
    ]
