# Generated by Django 2.2.4 on 2019-08-31 05:00

from django.db import migrations

from ontask.models import Workflow


def _adjust_boolean_operand(node):
    """Traverse the structure recursively and adjust boolean operand."""
    if 'condition' not in node:
        # Terminal case
        if node['type'] != 'boolean':
            # Done, the type is left unchanged
            return

        # Processing terminal case of type boolean
        node['type'] = 'string'
        if node['input'] == 'radio':
            node['input'] = 'select'

        if node['value'] == '1' or node['value'] == True:
            node['value'] = 'true'
        elif node['value'] == '0' or node['value'] == False:
            node['value'] = 'false'
        else:
            raise Exception('Incorrect formula found in migration.')
        return

    for subnode in node['rules']:
        _adjust_boolean_operand(subnode)


def refresh_query_builder_ops(apps, schema_editor):
    """Refresh the field of the query_builder_ops for each workflow."""
    for witem in Workflow.objects.all():
        witem.set_query_builder_ops()
        witem.save()


def refresh_condition_boolean(apps, schema_editor):
    """Refresh the structure of all the conditions.

    The reason for this change is because the operands of type boolean need
    to be modified from this structure:

    {'not': False,
     'rules': [{'id': 'registered',
     'type': 'boolean',
     'field': 'registered',
     'input': 'radio',
     'value': '1',
     'operator': 'equal'}],
     'valid': True,
     'condition': 'AND'}

     To this one

     {'not': False,
      'rules': [{'id': 'registered',
      'type': 'boolean',
      'field': 'registered',
      'input': 'select',    <---- DIFFERENT
      'value': 'Yes',       <---- DIFFERENT
      'operator': 'equal'}],
      'valid': True,
      'condition': 'AND'}
    """
    Condition = apps.get_model('ontask', 'Condition')
    for citem in Condition.objects.all():
        _adjust_boolean_operand(citem.formula)
        citem.save()


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0010_auto_20190828_1552'),
    ]

    operations = [
        migrations.RunPython(code=refresh_query_builder_ops),
        migrations.RunPython(code=refresh_condition_boolean)
    ]
