# Generated by Django 2.2.8 on 2019-12-08 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0010_auto_20191208_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledoperation',
            name='task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_operation', to='django_celery_beat.PeriodicTask'),
        ),
    ]
