# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-15 12:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0010_condition_n_selected_rows'),
    ]

    operations = [
        migrations.RenameField(
            model_name='condition',
            old_name='n_selected_rows',
            new_name='n_rows_selected',
        ),
    ]
