# Generated by Django 2.2.8 on 2019-12-08 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0011_auto_20191208_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledoperation',
            name='execute',
            field=models.DateTimeField(blank=True, null=True, verbose_name='When to execute this action'),
        ),
    ]
