# Generated by Django 2.2.4 on 2019-08-31 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0011_refresh_query_builder_ops'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='formula_txt',
            field=models.CharField(blank=True, default='', max_length=2048, null=True, verbose_name='formula text'),
        ),
    ]
