# Generated by Django 2.1.2 on 2018-11-11 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0011_auto_20181020_2206'),
        ('ontask', '0011_auto_20181020_2208'),
    ]

    operations = [
    ]
