# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-08 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0012_auto_20171208_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='column',
            name='valid_from',
        ),
        migrations.RemoveField(
            model_name='column',
            name='valid_to',
        ),
        migrations.AddField(
            model_name='column',
            name='active_from',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Column active from'),
        ),
        migrations.AddField(
            model_name='column',
            name='active_to',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Column active until'),
        ),
    ]
