# Generated by Django 2.2.4 on 2019-08-31 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0012_condition_formula_txt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='condition',
            old_name='formula_txt',
            new_name='formula_text',
        ),
    ]
