# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-30 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0012_remove_scheduledemailaction_add_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledemailaction',
            name='bcc_email',
            field=models.CharField(default='', max_length=2048, verbose_name='Comma-separated list of BCC Emails'),
        ),
        migrations.AddField(
            model_name='scheduledemailaction',
            name='cc_email',
            field=models.CharField(default='', max_length=2048, verbose_name='Comma-separated list of CC Emails'),
        ),
    ]
