# Generated by Django 2.1.3 on 2018-12-01 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0013_auto_20181126_1854'),
        ('ontask', '0012_merge_20181111_2142'),
    ]

    operations = [
    ]
