# Generated by Django 2.2.4 on 2019-09-02 07:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0013_auto_20190831_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='shared',
            field=models.ManyToManyField(blank=True, related_name='workflows_shared', to=settings.AUTH_USER_MODEL),
        ),
    ]
