# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-29 22:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0013_auto_20180530_0752'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sqlconnection',
            options={'ordering': ('Connection name',)},
        ),
        migrations.RenameField(
            model_name='sqlconnection',
            old_name='name',
            new_name='Connection name',
        ),
    ]
