# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-07 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0014_column_in_viz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='data_type',
            field=models.CharField(choices=[('datetime', 'datetime'), ('string', 'string'), ('boolean', 'boolean'), ('number', 'number')], max_length=512, verbose_name='Type of data to store in the column'),
        ),
    ]
