# Generated by Django 2.2.4 on 2019-09-02 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0014_auto_20190902_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='luser_email_column',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='luser_email_column', to='ontask.Column'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='lusers',
            field=models.ManyToManyField(blank=True, default=None, related_name='workflows_luser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='star',
            field=models.ManyToManyField(blank=True, related_name='workflows_star', to=settings.AUTH_USER_MODEL),
        ),
    ]
