# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-29 23:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0014_auto_20180530_0754'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sqlconnection',
            options={'ordering': ('name',)},
        ),
        migrations.RenameField(
            model_name='sqlconnection',
            old_name='Connection name',
            new_name='name',
        ),
    ]
