# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-08 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0015_auto_20180408_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='data_type',
            field=models.CharField(choices=[('boolean', 'boolean'), ('datetime', 'datetime'), ('string', 'string'), ('integer', 'integer'), ('double', 'double')], max_length=512, verbose_name='Type of data to store in the column'),
        ),
    ]
