# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-29 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0015_auto_20180530_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='sqlconnection',
            name='DB table name',
            field=models.CharField(default='', max_length=2048),
        ),
    ]
