# Generated by Django 2.2.5 on 2019-09-07 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0015_auto_20190902_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledaction',
            name='execute_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End of execution period'),
        ),
    ]
