# Generated by Django 2.2.8 on 2019-12-14 06:50

from django.db import migrations

from ontask import models


def change_action_types(apps, schema_editor):
    """Change the action type for some of the actions."""
    Old_Action = apps.get_model('ontask', 'Action')
    for action in Old_Action.objects.all():
        if action.action_type == 'send_list':
            action.action_type = models.Action.EMAIL_LIST
            action.save()
            continue

        if action.action_type == 'send_list_json':
            action.action_type = models.Action.JSON_LIST
            action.save()


def change_log_types(apps, schema_editor):
    """Change the log type for some of the logs"""

    Old_Log = apps.get_model('ontask', 'Log')
    for log_item in Old_Log.objects.all():
        if log_item.name == 'action_run_list':
            log_item.name = models.Log.ACTION_RUN_JSON_LIST
            log_item.save()
            continue

        if log_item.name == 'action_runjson':
            log_item.name = models.Log.ACTION_RUN_PERSONALIZED_JSON
            log_item.save()
            continue

        if log_item.name == 'action_run_send_list':
            log_item.name = models.Log.ACTION_RUN_EMAIL_LIST
            log_item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0015_auto_20191214_1720'),
    ]

    operations = [
        migrations.RunPython(code=change_action_types),
        migrations.RunPython(code=change_log_types),
    ]
