# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-30 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0016_sqlconnection_db table name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sqlconnection',
            name='Connection driver',
            field=models.CharField(blank=True, default='', help_text='Driver implementing the DBAPI', max_length=2048, verbose_name='Connection driver'),
        ),
    ]
