# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-23 06:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0016_auto_20180522_2146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='condition',
            options={'ordering': ('created',)},
        ),
        migrations.AlterUniqueTogether(
            name='condition',
            unique_together=set([('action', 'name', 'is_filter')]),
        ),
    ]
