# Generated by Django 2.2.5 on 2019-09-08 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0017_auto_20190908_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='action_type',
            field=models.CharField(choices=[('personalized_text', 'Personalized text'), ('personalized_canvas_email', 'Personalized Canvas Email'), ('survey', 'Survey'), ('personalized_json', 'Personalized JSON'), ('rubric_text', 'Rubric feedback'), ('send_list', 'Send List'), ('send_list_json', 'Send List as JSON'), ('todo_list', 'TODO List')], default='personalized_text', max_length=64),
        ),
    ]
