# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-30 02:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0017_sqlconnection_connection driver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sqlconnection',
            old_name='Connection driver',
            new_name='conn_driver',
        ),
        migrations.RenameField(
            model_name='sqlconnection',
            old_name='Connection type',
            new_name='conn_type',
        ),
        migrations.RenameField(
            model_name='sqlconnection',
            old_name='Host',
            new_name='db_host',
        ),
        migrations.RenameField(
            model_name='sqlconnection',
            old_name='DB name',
            new_name='db_name',
        ),
        migrations.RenameField(
            model_name='sqlconnection',
            old_name='Password',
            new_name='db_password',
        ),
        migrations.RenameField(
            model_name='sqlconnection',
            old_name='Port',
            new_name='db_port',
        ),
        migrations.RenameField(
            model_name='sqlconnection',
            old_name='DB table name',
            new_name='db_table',
        ),
        migrations.RenameField(
            model_name='sqlconnection',
            old_name='User name',
            new_name='db_user',
        ),
        migrations.RenameField(
            model_name='sqlconnection',
            old_name='Description',
            new_name='description_txt',
        ),
    ]
