# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-30 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0018_auto_20180530_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sqlconnection',
            name='conn_driver',
            field=models.CharField(blank=True, default='', help_text='Driver implementing the DBAPI', max_length=2048, verbose_name='Driver'),
        ),
        migrations.AlterField(
            model_name='sqlconnection',
            name='conn_type',
            field=models.CharField(help_text='Postgresql, Mysql, etc.', max_length=2048, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='sqlconnection',
            name='db_name',
            field=models.CharField(default='', max_length=2048, verbose_name='DB name'),
        ),
        migrations.AlterField(
            model_name='sqlconnection',
            name='db_table',
            field=models.CharField(default='', max_length=2048, verbose_name='Table'),
        ),
        migrations.AlterField(
            model_name='sqlconnection',
            name='db_user',
            field=models.CharField(blank=True, default='', max_length=2048, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='sqlconnection',
            name='description_txt',
            field=models.CharField(blank=True, default='', max_length=2048, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='sqlconnection',
            name='name',
            field=models.CharField(max_length=2048, unique=True, verbose_name='Name'),
        ),
    ]
