# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-26 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0018_auto_20180826_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledemailaction',
            name='type',
            field=models.CharField(choices=[('email_send', 'Send emails')], max_length=256),
        ),
    ]
