# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-16 10:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0019_action_shuffle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='shuffle',
        ),
    ]
