# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-29 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0019_auto_20180428_1606'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='column',
            options={'ordering': ('position',)},
        ),
        migrations.AlterField(
            model_name='column',
            name='position',
            field=models.IntegerField(default=1, verbose_name='Column position (zero to insert last)'),
        ),
    ]
