# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-30 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0019_auto_20180530_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sqlconnection',
            name='db_password',
            field=models.BooleanField(default=False, verbose_name='Password'),
        ),
    ]
