# Generated by Django 2.2.5 on 2019-09-11 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0020_rubriccell'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubriccell',
            name='level of attainment',
            field=models.IntegerField(default=0, verbose_name='level of attainment'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='rubriccell',
            unique_together={('action', 'column')},
        ),
        migrations.RemoveField(
            model_name='rubriccell',
            name='category',
        ),
    ]
