# Generated by Django 2.2.5 on 2019-09-11 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0021_auto_20190911_1617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rubriccell',
            old_name='level of attainment',
            new_name='loa_position',
        ),
        migrations.AlterUniqueTogether(
            name='rubriccell',
            unique_together={('action', 'column', 'loa_position')},
        ),
    ]
