# Generated by Django 2.1.4 on 2019-01-05 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0021_auto_20180530_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pluginregistry',
            name='executed',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Last verified'),
        ),
    ]
