# Generated by Django 2.2 on 2019-04-27 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0022_auto_20190106_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='pluginregistry',
            name='is_model',
            field=models.BooleanField(default=False, verbose_name='Plugin is a model'),
        ),
    ]
