# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-22 00:43
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0022_auto_20180510_1157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='column',
            options={'ordering': ('position',), 'verbose_name': 'column', 'verbose_name_plural': 'columns'},
        ),
        migrations.AlterModelOptions(
            name='workflow',
            options={'verbose_name': 'workflow', 'verbose_name_plural': 'workflows'},
        ),
        migrations.AlterField(
            model_name='column',
            name='categories',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True, verbose_name='comma separated list of values allowed'),
        ),
        migrations.AlterField(
            model_name='column',
            name='data_type',
            field=models.CharField(choices=[('boolean', 'boolean'), ('datetime', 'datetime'), ('string', 'string'), ('integer', 'integer'), ('double', 'double')], max_length=512, verbose_name='type of data to store in the column'),
        ),
        migrations.AlterField(
            model_name='column',
            name='description_text',
            field=models.CharField(blank=True, default='', max_length=2048, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='column',
            name='in_viz',
            field=models.BooleanField(default=True, verbose_name='include in visualization'),
        ),
        migrations.AlterField(
            model_name='column',
            name='is_key',
            field=models.BooleanField(default=False, verbose_name='has unique values per row'),
        ),
        migrations.AlterField(
            model_name='column',
            name='name',
            field=models.CharField(max_length=512, verbose_name='column name'),
        ),
        migrations.AlterField(
            model_name='column',
            name='position',
            field=models.IntegerField(default=0, verbose_name='column position (zero to insert last)'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='ncols',
            field=models.IntegerField(blank=True, default=0, verbose_name='number of columns'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='nrows',
            field=models.IntegerField(blank=True, default=0, verbose_name='number of rows'),
        ),
    ]
