# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-26 05:36
from __future__ import unicode_literals

from django.db import migrations


def combine_fields_into_payload(apps, schema_editor):
    if schema_editor.connection.alias != 'default':
        return

    # Traverse the scheduled actions and move the value from email_column to
    # item_column
    ScheduledAction = apps.get_model('ontask', 'ScheduledAction')
    for item in ScheduledAction.objects.all():
        payload = {}
        payload['subject'] = item.subject
        if item.cc_email:
            payload['cc_email'] = item.cc_email
        if item.bcc_email:
            payload['bcc_email'] = item.bcc_email
        payload['send_confirmation'] = item.send_confirmation
        payload['track_read'] = item.track_read
        item.payload = payload
        item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0023_auto_20180826_1505'),
    ]

    operations = [
        migrations.RunPython(combine_fields_into_payload),
    ]
