# Generated by Django 2.2.8 on 2019-12-29 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0023_auto_20191230_0837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledoperation',
            name='exclude_values',
        ),
    ]
