# Generated by Django 2.2.8 on 2019-12-30 05:44

from django.db import migrations


def move_item_column_to_payload(apps, schema_editor):
    if schema_editor.connection.alias != 'default':
        return

    # Traverse the scheduled actions and move the exclude_items field from
    # the object field to the payload
    ScheduledOperation = apps.get_model('ontask', 'ScheduledOperation')
    for item in ScheduledOperation.objects.all():
        if item.item_column:
            item.payload['item_column'] = item.item_column.id
            item.save()


class Migration(migrations.Migration):
    """Move item_column to the paylaod."""

    dependencies = [
        ('ontask', '0024_remove_scheduledoperation_exclude_values'),
    ]

    operations = [
        migrations.RunPython(move_item_column_to_payload),
    ]
