# Generated by Django 2.2.8 on 2019-12-30 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0025_auto_20191230_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledoperation',
            name='item_column',
        ),
    ]
