# Generated by Django 2.2.8 on 2020-01-01 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0026_remove_scheduledoperation_item_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sqlconnection',
            name='db_table',
            field=models.CharField(blank=True, default='', help_text='Leave empty to enter at execution', max_length=2048, null=True, verbose_name='Database table'),
        ),
    ]
