# Generated by Django 2.2.1 on 2019-05-24 02:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('ontask', '0028_auto_20190418_1550'), ('ontask', '0029_auto_20190418_1554'), ('ontask', '0030_remove_workflow_lusers'), ('ontask', '0031_workflow_lusers'), ('ontask', '0032_auto_20190419_0819'), ('ontask', '0033_workflow_lusers_is_outdated'), ('ontask', '0034_auto_20190422_1226'), ('ontask', '0035_auto_20190430_1922')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ontask', '0027_auto_20190418_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='shared',
            field=models.ManyToManyField(related_name='workflows_shared', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workflow',
            name='lusers',
            field=models.ManyToManyField(default=None, related_name='workflows_luser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workflow',
            name='lusers_is_outdated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterModelOptions(
            name='column',
            options={'ordering': ['position'], 'verbose_name': 'column', 'verbose_name_plural': 'columns'},
        ),
    ]
