# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-07 07:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0025_auto_20180806_0742'),
        ('ontask', '0027_auto_20180723_1019'),
    ]

    operations = [
    ]
