# Generated by Django 2.2.5 on 2019-09-24 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0027_auto_20190921_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='actioncolumnconditiontuple',
            name='changes_allowed',
            field=models.BooleanField(default=True, verbose_name='Allow changes?'),
        ),
    ]
