# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-14 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0028_merge_20180807_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='action_type',
            field=models.CharField(choices=[('personal_text', 'Personalized text'), ('json', 'Personalized JSON'), ('survey', 'Survey'), ('todolist', 'TODO List')], default='personal_text', max_length=64),
        ),
    ]
