# Generated by Django 2.2.5 on 2019-09-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0028_actioncolumnconditiontuple_changes_allowed'),
    ]

    operations = [
        migrations.CreateModel(
            name='AthenaConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2048, unique=True, verbose_name='Name')),
                ('description_text', models.CharField(blank=True, default='', max_length=2048, verbose_name='Description')),
                ('aws_access_key', models.CharField(default='', max_length=512, verbose_name='AWS access key')),
                ('aws_secret_access_key', models.CharField(default='', max_length=512, verbose_name='AWS secret access key')),
                ('aws_bucket_name', models.CharField(default='', max_length=512, verbose_name='AWS S3 Bucket name (no s3:// prefix)')),
                ('aws_file_path', models.CharField(default='', max_length=512, verbose_name='AWS S3 Bucket file path')),
                ('aws_region_name', models.CharField(default='', max_length=512, verbose_name='AWS region name')),
                ('table', models.CharField(default='', max_length=2048, verbose_name='Table name')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
