# Generated by Django 2.2.10 on 2020-05-02 01:20

from django.db import migrations


def change_action_type(apps, schema_editor):
    """
    Traverse all actions to change personal_text by personalized_text

    :param apps:
    :param schema_editor:
    :return:
    """
    if schema_editor.connection.alias != 'default':
        return

    Action = apps.get_model('ontask', 'Action')
    for item in Action.objects.all():
        if item.action_type == 'email_list':
            item.action_type = 'email_report'
            item.save()
            continue

        if item.action_type == 'json_list':
            item.action_type = 'json_report'
            item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0029_auto_20200502_1048'),
    ]

    operations = [
        migrations.RunPython(change_action_type),
    ]
