# Generated by Django 2.2.10 on 2020-05-03 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0030_auto_20200502_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='attachments',
            field=models.ManyToManyField(related_name='attached_to', to='ontask.View', verbose_name='Email attachments'),
        ),
    ]
