# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-29 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0030_remove_scheduledaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledaction',
            name='description_text',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='scheduledaction',
            name='name',
            field=models.CharField(default='Scheduled action', max_length=256, verbose_name='name'),
            preserve_default=False,
        ),
    ]
