# Generated by Django 2.2.5 on 2019-09-29 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0030_auto_20190928_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athenaconnection',
            name='table',
        ),
    ]
