# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-18 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0031_auto_20180818_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='target_url',
            field=models.TextField(default=''),
        ),
    ]
