# Generated by Django 2.2 on 2019-04-19 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0032_auto_20190419_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='lusers_is_outdated',
            field=models.BooleanField(default=False, verbose_name='Is lusers outdated?'),
        ),
    ]
