# Generated by Django 2.2.5 on 2019-09-30 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0032_auto_20190930_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='athenaconnection',
            name='table_name',
            field=models.CharField(blank=True, default='', max_length=512, null=True, verbose_name='Table name'),
        ),
    ]
