# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-19 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0033_auto_20180818_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='target_url',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
