# Generated by Django 2.2.5 on 2019-10-01 01:48

from django.db import migrations
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0033_athenaconnection_table_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athenaconnection',
            name='aws_secret_access_key',
            field=fernet_fields.fields.EncryptedCharField(default='', max_length=512, verbose_name='AWS secret access key'),
        ),
    ]
