# Generated by Django 2.2.5 on 2019-10-01 22:37

from django.db import migrations, models
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0034_auto_20191001_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='sqlconnection',
            name='db_password2',
            field=fernet_fields.fields.EncryptedCharField(blank=True, default=False, max_length=2048, null=True, verbose_name='Password (leave empty to enter when executing)'),
        ),
        migrations.AlterField(
            model_name='sqlconnection',
            name='db_table',
            field=models.CharField(blank=True, default='', max_length=2048, null=True, verbose_name='Table'),
        ),
    ]
