# Generated by Django 2.2.24 on 2023-03-29 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0034_auto_20200517_1933'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_template', models.TextField(default='\n<html>\n<head/>\n<body>\n<p>Dear {{ user.name }}</p>\n\n<p>This message is to inform you that on {{ email_sent_datetime }}\n{{ num_messages }} email{% if num_messages > 1 %}s{% endif %} were sent\nresulting from the execution of the action with name "{{ action.name }}".</p>\n\n{% if filter_present %}\n<p>The action had a filter that reduced the number of messages from\n{{ num_rows }} to {{ num_selected }}.</p>\n{% else %}\n<p>All the data rows stored in the workflow table were used.</p>\n{% endif %}\n\nRegards.\nThe OnTask Support Team\n</body></html>')),
                ('notification_subject', models.CharField(default='OnTask: Action executed', max_length=1024)),
                ('notification_sender', models.CharField(default='abelardo.pardo@unisa.edu.au', max_length=1024)),
                ('content_types', models.TextField(blank=True, default='["text/csv", "application/json", "application/gzip", "application/x-gzip", "application/vnd.ms-excel"]')),
                ('max_upload_size', models.IntegerField(blank=True, default=209715200)),
                ('plugin_directory', models.CharField(blank=True, default='/Users/pardosa/ontask_b/lib/plugins', max_length=2048)),
                ('max_log_list_size', models.IntegerField(blank=True, default=200)),
                ('help_url', models.CharField(blank=True, default='html/index.html', max_length=256)),
            ],
            options={
                'verbose_name': 'Preference',
                'verbose_name_plural': 'Preferences',
                'managed': False,
            },
        ),
    ]
