# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-29 03:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0034_auto_20180829_0943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledaction',
            name='deleted',
        ),
    ]
