# Generated by Django 2.2.24 on 2023-03-30 01:10

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion

from ontask.core import fix_non_unique_object_names


def fix_non_unique_condition_names(apps, schema_editor):
    """Disambiguate conditions with identical names within an action."""

    Action = apps.get_model('ontask', 'Action')
    for action in Action.objects.all():
        # Loop over the actions to make the conditions unique

        # Get the condition names and those with duplicate names
        cond_names = set()
        dupes = [
            cond for cond in action.conditions.all()
            if cond.name in cond_names or cond_names.add(cond.name)]

        if not dupes:
            # No duplicates, nothing to do here
            continue

        fix_non_unique_object_names(cond_names, dupes)


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0035_preferences'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='condition',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='condition',
            name='workflow',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='ontask.Workflow'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='name',
            field=models.CharField(max_length=1024, verbose_name='name'),
        ),
        migrations.RunPython(code=fix_non_unique_condition_names),
        migrations.AlterUniqueTogether(
            name='condition',
            unique_together={('action', 'name')},
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('formula', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True, verbose_name='formula')),
                ('formula_text', models.CharField(blank=True, default='', max_length=2048, null=True, verbose_name='formula text')),
                ('n_rows_selected', models.IntegerField(default=-1, verbose_name='Number of rows selected')),
                ('description_text', models.CharField(blank=True, default='', max_length=2048, verbose_name='description')),
                ('action_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ontask.Action')),
                ('columns', models.ManyToManyField(related_name='filters', to='ontask.Column', verbose_name='Columns present in this filter')),
                ('workflow', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='ontask.Workflow')),
            ],
        ),
    ]
