# Generated by Django 2.2.5 on 2019-10-01 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0035_auto_20191002_0807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sqlconnection',
            name='db_password',
        ),
    ]
