# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-19 11:38
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0004_log_modified'),
        ('ontask', '0035_action_last_executed'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='last_executed_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ontask.Log'),
        ),
    ]
