# Generated by Django 2.2.24 on 2023-03-30 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0037_auto_20230330_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condition',
            name='is_filter',
        ),
        migrations.AddField(
            model_name='action',
            name='filter',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ontask.Filter'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='workflow',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='ontask.Workflow'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='action_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_ref', to='ontask.Action'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='workflow',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='ontask.Workflow'),
        ),
    ]
