# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-04 21:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0038_auto_20180826_1505'),
        ('ontask', '0029_auto_20180814_1400'),
    ]

    operations = [
    ]
