# Generated by Django 2.2.13 on 2020-08-16 06:58

from django.db import migrations


def set_action_filter(apps, schema_editor):
    """Separate conditions and filters into two tables."""

    Filter = apps.get_model('ontask', 'Filter')
    for fitem in Filter.objects.all():
        fitem.action_ref.filter = fitem
        fitem.action_ref.save()


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0038_auto_20230330_1233'),
    ]

    operations = [
        migrations.RunPython(code=set_action_filter),
    ]
