# Generated by Django 2.2.5 on 2019-10-02 01:16

import fernet_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0038_auto_20191002_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athenaconnection',
            name='aws_secret_access_key',
            field=fernet_fields.fields.EncryptedCharField(blank=True, default='', help_text='Leave blank to provide at execution', max_length=512, null=True, verbose_name='AWS secret access key'),
        ),
        migrations.AlterField(
            model_name='athenaconnection',
            name='table_name',
            field=models.CharField(blank=True, default='', help_text='Leave blank to provide at execution', max_length=512, null=True, verbose_name='Table name'),
        ),
    ]
