# Generated by Django 2.2.24 on 2023-03-30 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0039_auto_20230330_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filter',
            name='action_ref',
        ),
    ]
