# Generated by Django 2.2.24 on 2023-03-30 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0040_auto_20230330_1345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='condition',
            old_name='formula',
            new_name='_formula',
        ),
        migrations.RenameField(
            model_name='condition',
            old_name='formula_text',
            new_name='_formula_text',
        ),
        migrations.RenameField(
            model_name='filter',
            old_name='formula',
            new_name='_formula',
        ),
        migrations.RenameField(
            model_name='filter',
            old_name='formula_text',
            new_name='_formula_text',
        ),
        migrations.RenameField(
            model_name='view',
            old_name='formula',
            new_name='_formula',
        ),
        migrations.AddField(
            model_name='filter',
            name='view',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='view', to='ontask.View'),
        ),
    ]
