# Generated by Django 2.2.24 on 2023-03-31 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0041_auto_20230330_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='view',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filter', to='ontask.View'),
        ),
    ]
