# Generated by Django 2.2.5 on 2019-10-04 10:44

from django.db import migrations
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0041_auto_20191004_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sqlconnection',
            name='db_password',
            field=fernet_fields.fields.EncryptedCharField(blank=True, default='', help_text='Leave empty to enter at execution', max_length=2048, null=True, verbose_name='Password'),
        ),
    ]
