# Generated by Django 2.2.5 on 2019-10-06 06:10

from django.db import migrations, models
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0042_auto_20191004_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='athenaconnection',
            name='aws_session_token',
            field=fernet_fields.fields.EncryptedTextField(blank=True, default='', help_text='Leave blank to provide at execution', null=True, verbose_name='AWS session token'),
        ),
        migrations.AlterField(
            model_name='athenaconnection',
            name='aws_file_path',
            field=models.CharField(blank=True, default='', max_length=512, null=True, verbose_name='AWS S3 Bucket file path'),
        ),
    ]
