# Generated by Django 2.1.3 on 2018-12-12 02:53

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0042_auto_20181212_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='formula',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True, verbose_name='formula'),
        ),
    ]
