# Generated by Django 2.2.5 on 2019-10-06 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0043_auto_20191006_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='athenaconnection',
            name='enabled',
            field=models.BooleanField(default=False, verbose_name='Available to users?'),
        ),
        migrations.AddField(
            model_name='sqlconnection',
            name='enabled',
            field=models.BooleanField(default=False, verbose_name='Available to users?'),
        ),
    ]
