# Generated by Django 2.2.24 on 2023-03-31 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0043_auto_20230331_1159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='condition',
            old_name='n_rows_selected',
            new_name='selected_count',
        ),
        migrations.RenameField(
            model_name='filter',
            old_name='n_rows_selected',
            new_name='selected_count',
        ),
    ]
