# Generated by Django 2.1.7 on 2019-02-28 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0045_columnconditionpair'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='columns',
            field=models.ManyToManyField(to='workflow.Column'),
        ),
    ]
