# Generated by Django 2.2.24 on 2023-03-31 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0046_action_filter_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filter',
            name='action',
        ),
    ]
