# Generated by Django 2.1.7 on 2019-02-28 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0024_auto_20180925_1934'),
        ('ontask', '0047_columnconditionpair_action'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='columnconditionpair',
            unique_together={('action', 'column', 'condition')},
        ),
    ]
