# Generated by Django 2.2.24 on 2023-03-31 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0047_remove_filter_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='filter_new',
        ),
        migrations.AddField(
            model_name='action',
            name='filter',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action', to='ontask.Filter'),
        ),
    ]
