# Generated by Django 2.2.6 on 2019-10-23 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0048_auto_20191016_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='name',
            field=models.CharField(max_length=512, verbose_name='name'),
        ),
    ]
