# Generated by Django 2.2.24 on 2023-03-31 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0048_auto_20230331_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='filter',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action', to='ontask.Filter'),
        ),
    ]
