# Generated by Django 2.2.24 on 2023-03-31 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0049_auto_20230331_1311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'ordering': ['action_type', 'name']},
        ),
    ]
