# Generated by Django 2.2.6 on 2019-10-23 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0049_auto_20191024_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='name',
            field=models.CharField(max_length=512, verbose_name='name'),
        ),
    ]
