# Generated by Django 2.2.24 on 2023-03-31 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0050_auto_20230331_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='filter',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='ontask.Filter'),
        ),
    ]
