# Generated by Django 2.2.6 on 2019-10-23 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0051_auto_20191024_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledoperation',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='scheduledoperation',
            name='name',
            field=models.CharField(max_length=512, verbose_name='name'),
        ),
    ]
