# Generated by Django 2.2.24 on 2023-03-31 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0051_auto_20230331_1728'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
