# Generated by Django 2.1.7 on 2019-02-28 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0051_auto_20190228_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actioncolumnconditiontuple',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='column_condition_pair', to='ontask.Action'),
        ),
    ]
