# Generated by Django 2.1.7 on 2019-03-18 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0053_remove_action_columns'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actioncolumnconditiontuple',
            options={'ordering': ['column__position']},
        ),
    ]
