# Generated by Django 2.2.6 on 2019-10-26 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0055_auto_20191026_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='name',
            field=models.CharField(max_length=63, verbose_name='column name'),
        ),
    ]
