# Generated by Django 2.1.7 on 2019-03-23 02:57

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0056_auto_20190323_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='rows_all_false',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True),
        ),
    ]
