# Generated by Django 2.2.6 on 2019-10-26 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0056_auto_20191026_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='name',
            field=models.CharField(max_length=512, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='name',
            field=models.CharField(blank=True, max_length=512, verbose_name='name'),
        ),
    ]
