# Generated by Django 2.2.6 on 2019-10-27 07:39

from django.db import migrations


def update_scheduled_op_workflow_field(apps, schema_editor):
    """Traverse scheduled ops and assign value to workflow."""

    ScheduledOperation = apps.get_model('ontask', 'ScheduledOperation')
    for sch_item in ScheduledOperation.objects.all():
        sch_item.workflow = sch_item.action.workflow
        sch_item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0059_auto_20191027_1740'),
    ]

    operations = [
        migrations.RunPython(update_scheduled_op_workflow_field),
    ]
