# Generated by Django 2.2 on 2019-05-21 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0061_auto_20190430_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='target_url',
            field=models.TextField(blank=True, default=''),
        ),
    ]
