# Generated by Django 2.2.6 on 2019-12-01 01:38

from django.db import migrations, models
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0064_auto_20191123_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='name',
            field=models.CharField(max_length=1024, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='athenaconnection',
            name='aws_access_key',
            field=models.CharField(default='', max_length=1024, verbose_name='AWS access key'),
        ),
        migrations.AlterField(
            model_name='athenaconnection',
            name='aws_bucket_name',
            field=models.CharField(default='', max_length=1024, verbose_name='AWS S3 Bucket name (no s3:// prefix)'),
        ),
        migrations.AlterField(
            model_name='athenaconnection',
            name='aws_file_path',
            field=models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='AWS S3 Bucket file path'),
        ),
        migrations.AlterField(
            model_name='athenaconnection',
            name='aws_region_name',
            field=models.CharField(default='', max_length=1024, verbose_name='AWS region name'),
        ),
        migrations.AlterField(
            model_name='athenaconnection',
            name='aws_secret_access_key',
            field=fernet_fields.fields.EncryptedCharField(blank=True, default='', help_text='Leave blank to provide at execution', max_length=1024, null=True, verbose_name='AWS secret access key'),
        ),
        migrations.AlterField(
            model_name='athenaconnection',
            name='name',
            field=models.CharField(max_length=1024, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='athenaconnection',
            name='table_name',
            field=models.CharField(blank=True, default='', help_text='Leave blank to provide at execution', max_length=1024, null=True, verbose_name='Table name'),
        ),
        migrations.AlterField(
            model_name='column',
            name='data_type',
            field=models.CharField(choices=[('string', 'string'), ('integer', 'integer'), ('double', 'double'), ('boolean', 'boolean'), ('datetime', 'datetime')], max_length=1024, verbose_name='type of data to store in the column'),
        ),
        migrations.AlterField(
            model_name='column',
            name='name',
            field=models.CharField(max_length=1024, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='name',
            field=models.CharField(blank=True, max_length=1024, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='log',
            name='name',
            field=models.CharField(choices=[('action_clone', 'Action cloned'), ('action_create', 'Action created'), ('action_delete', 'Action deleted'), ('download_zip_action', 'Download a ZIP with one file per text'), ('action_email_notify', 'Notification email sent'), ('action_email_read', 'Email read'), ('action_email_sent', 'Emails sent'), ('action_import', 'Action imported'), ('action_json_sent', 'Emails sent'), ('action_list_email_sent', 'Email with data list sent'), ('question_add', 'Question added'), ('question_toggle_changes', 'Question toggle changes'), ('action_rubric_criterion_add', 'Add a rubric criterion'), ('action_rubric_criterion_edit', 'Edit rubric criterion'), ('action_rubric_criterion_delete', 'Delete rubric criterion'), ('action_rubriccell_edit', 'Rubric cell edit'), ('action_rubric_loa_edit', 'Rubric level of attainment edit'), ('action_run_canvas_email', 'Execute scheduled canvas email action'), ('schedule_email_execute', 'Execute scheduled email action'), ('schedule_json_execute', 'Execute scheduled JSON action'), ('schedule_json_list_execute', 'Execute scheduled JSON list action'), ('schedule_send_list_execute', 'Execute scheduled send list action'), ('zip_messages_execute', 'Create a zip with personalized content'), ('action_serve_toggled', 'Action URL toggled'), ('action_served_execute', 'Action served'), ('survey_input', 'Survey data input'), ('action_update', 'Action updated'), ('athena_connection_clone', 'Athena connection cloned'), ('athena_connection_create', 'Athena connection created'), ('athena_connection_delete', 'Athena connection deleted'), ('athena_connection_edit', 'Athena connection updated'), ('athena_connection_toggle', 'SQL connection toggled'), ('column_add', 'Column added'), ('column_add_formula', 'Column with formula created'), ('column_add_random', 'Column with random values created'), ('column_clone', 'Column cloned'), ('column_delete', 'Column deleted'), ('column_edit', 'Column edited'), ('column_restrict', 'Column restricted'), ('condition_clone', 'Condition cloned'), ('condition_create', 'Condition created'), ('condition_delete', 'Condition deleted'), ('condition_update', 'Condition updated'), ('plugin_create', 'Plugin created'), ('plugin_delete', 'Plugin deleted'), ('plugin_execute', 'Plugin executed'), ('plugin_update', 'Plugin updated'), ('schedule_create', 'Create scheduled operation'), ('schedule_edit', 'Edit scheduled operation'), ('schedule_delete', 'Delete scheduled operation'), ('sql_connection_clone', 'SQL connection cloned'), ('sql_connection_create', 'SQL connection created'), ('sql_connection_delete', 'SQL connection deleted'), ('sql_connection_edit', 'SQL connection updated'), ('sql_connection_toggle', 'SQL connection toggled'), ('view_create', 'Table view created'), ('view_edit', 'Table view edited'), ('view_delete', 'Table view deleted'), ('view_clone', 'Table view cloned'), ('workflow_attribute_create', 'New attribute in workflow'), ('workflow_attribute_update', 'Attributes updated in workflow'), ('workflow_attribute_delete', 'Attribute deleted'), ('workflow_clone', 'Workflow cloned'), ('workflow_create', 'Workflow created'), ('workflow_data_failedmerge', 'Failed data merge into workflow'), ('workflow_data_flush', 'Workflow data flushed'), ('workflow_data_merge', 'Data merged into workflow'), ('tablerow_create', 'Table row created'), ('tablerow_update', 'Table row updated'), ('workflow_data_upload', 'Data uploaded to workflow'), ('workflow_delete', 'Workflow deleted'), ('workflow_import', 'Import workflow'), ('workflow_increase_track_count', 'Increase workflow track count.'), ('workflow_share_add', 'User share added'), ('workflow_share_delete', 'User share deleted'), ('workflow_star', 'Toggle workflow star'), ('workflow_update', 'Workflow updated'), ('workflow_update_lusers', 'Update list of workflow users')], max_length=1024),
        ),
        migrations.AlterField(
            model_name='plugin',
            name='name',
            field=models.CharField(max_length=1024, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='scheduledoperation',
            name='name',
            field=models.CharField(max_length=1024, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='scheduledoperation',
            name='operation_type',
            field=models.CharField(choices=[('run_action_personalized_text', 'Run personalized text action'), ('run_action_personalized_json', 'Run personalized JSON action'), ('run_action_send_list', 'Run send list action'), ('run_action_send_list_json', 'Run send JSON list action'), ('run_action_rubric_text', 'Run rubrict text action')], max_length=1024),
        ),
        migrations.AlterField(
            model_name='sqlconnection',
            name='name',
            field=models.CharField(max_length=1024, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='view',
            name='name',
            field=models.CharField(max_length=1024, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='name',
            field=models.CharField(max_length=1024, verbose_name='name'),
        ),
    ]
