# Generated by Django 3.2.10 on 2022-01-31 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0065_auto_20220131_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actioncolumnconditiontuple',
            name='condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='column_condition_pair', to='ontask.condition'),
        ),
    ]
