# Generated by Django 3.2.15 on 2023-04-02 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0066_alter_actioncolumnconditiontuple_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='filter',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='ontask.filter'),
        ),
    ]
