# Generated by Django 4.2.7 on 2023-12-03 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0069_alter_athenaconnection_aws_file_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledoperation',
            name='operation_type',
            field=models.CharField(choices=[('action_run_personalized_email', 'Execute scheduled email action'), ('action_run_personalized_canvas_email', 'Execute scheduled canvas email action'), ('action_run_personalized_json', 'Execute scheduled JSON action'), ('action_run_json_report', 'Execute scheduled JSON report action'), ('action_run_email_report', 'Execute scheduled send report action'), ('workflow_increase_track_count', 'Increase workflow track count.'), ('plugin_execute', 'Plugin executed'), ('workflow_update_lusers', 'Update list of workflow users')], max_length=1024),
        ),
    ]
