# Generated by Django 4.2.7 on 2023-12-24 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0073_alter_log_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sqlconnection',
            name='db_table',
            field=models.CharField(default='', help_text='Table name', max_length=2048, verbose_name='Database table'),
        ),
    ]
