# Generated by Django 4.2.7 on 2023-12-24 07:04

from django.db import migrations, models


def set_table_default_name(apps, schema_editor):
    """Set the table default name"""
    SQLConnection = apps.get_model('ontask', 'SQLConnection')
    for s_conn in SQLConnection.objects.all():
        if not s_conn.db_table:
            s_conn.db_table = 'INCORRECT_TABLE_DEFAULT_NAME'
            s_conn.save()


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0074_alter_sqlconnection_db_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sqlconnection',
            name='db_table',
            field=models.CharField(help_text='Table name', max_length=2048, verbose_name='Database table'),
        ),
        migrations.RunPython(code=set_table_default_name),
    ]
