# Generated by Django 4.2.7 on 2023-12-24 23:22

from django.db import migrations
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0076_alter_oauthusertoken_instance_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauthusertoken',
            name='access_token',
            field=fernet_fields.fields.EncryptedCharField(max_length=2048),
        ),
    ]
