# Generated by Django 4.2.7 on 2023-12-25 00:47

from django.db import migrations, models
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0077_alter_oauthusertoken_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauthusertoken',
            name='instance_name',
            field=models.CharField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='oauthusertoken',
            name='refresh_token',
            field=fernet_fields.fields.EncryptedCharField(blank=True, max_length=2048),
        ),
    ]
