# Generated by Django 4.2.7 on 2023-12-25 06:01

from django.db import migrations
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ontask', '0078_alter_oauthusertoken_instance_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sqlconnection',
            name='db_password',
            field=fernet_fields.fields.EncryptedCharField(blank=True, default='', max_length=2048, verbose_name='Password'),
        ),
    ]
