# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_workflow_shared'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='description_text',
            field=models.CharField(blank=True, default='', max_length=2048),
        ),
    ]
