# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-22 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('workflow', '0022_auto_20180510_1157'),
        ('action', '0012_remove_action_n_selected_rows'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='columns',
            field=models.ManyToManyField(related_name='conditions',
                                         to='workflow.Column',
                                         verbose_name='Columns present in this condition'),
        ),
    ]
