# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-22 00:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0024_auto_20180630_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='is_out',
            field=models.BooleanField(default=True, verbose_name='Action to provide personalized information'),
        ),
    ]
