# Generated by Django 2.1.7 on 2019-03-23 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0057_action_rows_all_false'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='nrows_all_false',
        ),
    ]
