# Generated by Django 2.2 on 2019-04-18 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190418_2038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ontaskuser',
            options={'verbose_name': 'ontaskuser', 'verbose_name_plural': 'ontaskusers'},
        ),
    ]
