# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-07 07:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataops', '0004_auto_20171124_0604'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rowview',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='rowview',
            name='columns',
        ),
        migrations.RemoveField(
            model_name='rowview',
            name='workflow',
        ),
        migrations.DeleteModel(
            name='RowView',
        ),
    ]
