# Generated by Django 2.2.3 on 2019-08-02 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataops', '0004_plugin_is_enabled'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='plugin',
            table='plugin',
        ),
        migrations.AlterModelTable(
            name='sqlconnection',
            table='sql_connection',
        ),
    ]
