# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-25 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataops', '0007_auto_20180523_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='pluginregistry',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Is it ready to run?'),
        ),
    ]
