# Generated by Django 2.2 on 2019-05-10 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataops', '0024_auto_20190430_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pluginregistry',
            name='description_txt',
            field=models.CharField(blank=True, default='', max_length=65536),
        ),
    ]
