# Generated by Django 2.1.3 on 2018-12-19 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0015_auto_20181207_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='workflow',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='workflow.Workflow'),
        ),
    ]
