User.objects.create(email='instructor1@bogus.com', password='boguspwd')
User.objects.create(email='instructor2@bogus.com', password='boguspwd')
User.objects.create(email='instructor3@bogus.com', password='boguspwd')
User.objects.create(email='student1@bogus.com', password='boguspwd')
User.objects.create(email='student2@bogus.com', password='boguspwd')
User.objects.create(email='student3@bogus.com', password='boguspwd')
