User.objects.create_user(email='instructor01@bogus.com', password='boguspwd')
User.objects.create_user(email='instructor02@bogus.com', password='boguspwd')
User.objects.create_user(email='instructor03@bogus.com', password='boguspwd')
User.objects.create_user(email='student01@bogus.com', password='boguspwd')
User.objects.create_user(email='student02@bogus.com', password='boguspwd')
User.objects.create_user(email='student03@bogus.com', password='boguspwd')
