# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 09:52
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0005_auto_20171125_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='workflow',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='workflow.Workflow'),
        ),
    ]
