# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-08 12:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0008_auto_20171208_2139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='column',
            old_name='Valid from',
            new_name='valid_from',
        ),
        migrations.RenameField(
            model_name='column',
            old_name='Valid until',
            new_name='valid_to',
        ),
    ]
