# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-23 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0013_auto_20171209_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='in_viz',
            field=models.BooleanField(default=True, verbose_name='Include in visualization'),
        ),
    ]
