# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-29 01:57
from __future__ import unicode_literals

from django.db import migrations
from dataops import pandas_db


def forwards(apps, schema_editor):
    if schema_editor.connection.alias != 'default':
        return
    # Traverse the workflows and verify that the columns are in the same
    # order than the columns in the workflow
    Workflow = apps.get_model('workflow', 'Workflow')

    for w in Workflow.objects.all():
        if not pandas_db.is_wf_table_in_db(w):
            continue

        df = pandas_db.load_table(w.id)

        if len(df.columns) != w.ncols:
            raise Exception('Inconsistent number of columns')

        df_columns = list(df.columns)
        for c in w.columns.all():
            c.position = df_columns.index(c.name) + 1
            c.save()


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0021_auto_20180429_1157'),
    ]

    operations = [
        migrations.RunPython(forwards),
    ]
