# Generated by Django 2.2 on 2019-04-18 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0026_auto_20190319_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='luser_email_column',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='luser_email_column', to='workflow.Column'),
        ),
        migrations.AddField(
            model_name='workflow',
            name='luser_email_column_md5',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
