# Generated by Django 2.2 on 2019-04-18 22:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0031_workflow_lusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='lusers',
            field=models.ManyToManyField(default=None, related_name='workflows_luser', to=settings.AUTH_USER_MODEL),
        ),
    ]
