# Generated by Django 2.2.1 on 2019-06-02 02:44

import pandas as pd

from django.db import migrations

from dataops.pandas.db import (
    is_table_in_db, engine, store_table, ontask_index_column,
)
from dataops.sql import df_drop_column, is_column_in_table


def add_index_column_to_dataframes(apps, schema_editor):
    """Add an extra index columns to all data frames.

    Traverses the database tables and for those that start with the OnTask
    prefix, loads them as a data frame, and are written again with an extra
    column for the index. This is useful to facilitate row edition and deletion
    without relying on the key columns.
    """
    for wflow in apps.get_model('workflow', 'Workflow').objects.all():
        tname = '__ONTASK_WORKFLOW_TABLE_{0}'.format(wflow.id)
        tname2 = '__ONTASK_WORKFLOW_TABLE_UPLOAD_{0}'.format(wflow.id)

        if is_table_in_db(tname):
            # Load/dump table
            data_frame = pd.read_sql_table(tname, engine)
            store_table(data_frame, tname)

        if is_table_in_db(tname2):
            # Load/dump table
            data_frame = pd.read_sql_table(tname2, engine)
            store_table(data_frame, tname2)


def remove_index_column(apps, schema_editor):
    """Remove extra index column from data frame tables."""
    for wflow in apps.get_model('workflow', 'Workflow').objects.all():
        tname = '__ONTASK_WORKFLOW_TABLE_{0}'.format(wflow.id)
        tname2 = '__ONTASK_WORKFLOW_TABLE_UPLOAD_{0}'.format(wflow.id)

        if is_table_in_db(tname) and is_column_in_table(
            tname,
            ontask_index_column
        ):
            df_drop_column(tname, ontask_index_column)

        if is_table_in_db(tname2) and is_column_in_table(
            tname2,
            ontask_index_column
        ):
            df_drop_column(tname2, ontask_index_column)


class Migration(migrations.Migration):

    dependencies = [
        ('dataops', '0001_squashed_0025_auto_20190510_1928'),
    ]

    operations = [
        migrations.RunPython(
            code=add_index_column_to_dataframes,
            reverse_code=remove_index_column,
        ),
    ]
