# Generated by Django 2.2.1 on 2019-06-08 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataops', '0002_auto_20190607_0921'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plugin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=2048, unique=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256)),
                ('description_txt', models.CharField(blank=True, default='', max_length=65536)),
                ('is_model', models.BooleanField(blank=True, default=None, null=True, verbose_name='Is a model')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Ready to run')),
                ('executed', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Last verified')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='PluginRegistry',
        ),
    ]
