# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-17 13:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_scheduledemailaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledemailaction',
            name='execute',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 20, 22, 23)),
            preserve_default=False,
        ),
    ]
