# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-17 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_auto_20171218_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledemailaction',
            name='execute',
            field=models.DateTimeField(verbose_name='When to execute this action'),
        ),
    ]
