# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-17 19:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0007_auto_20171218_0100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledemailaction',
            name='workflow',
        ),
    ]
