# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-19 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0010_scheduledemailaction_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledemailaction',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
