# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-26 04:39
from __future__ import unicode_literals

from django.db import migrations


def reassign_email_to_item(apps, schema_editor):
    if schema_editor.connection.alias != 'default':
        return

    # Traverse the scheduled actions and move the value from email_column to
    # item_column
    ScheduledEmailAction = apps.get_model('scheduler', 'ScheduledEmailAction')
    for item in ScheduledEmailAction.objects.all():
        item.item_column = item.email_column
        item.save()

class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0016_auto_20180826_1408'),
    ]

    operations = [
        migrations.RunPython(reassign_email_to_item),
    ]
