# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-26 04:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0017_auto_20180826_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledemailaction',
            name='email_column',
        ),
        migrations.AlterField(
            model_name='scheduledemailaction',
            name='item_column',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_actions', to='workflow.Column', verbose_name='Column to select the elements for the action'),
        ),
    ]
