# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-26 09:00
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0006_auto_20180825_1123'),
        ('scheduler', '0024_auto_20180826_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledaction',
            name='message',
        ),
        migrations.AddField(
            model_name='scheduledaction',
            name='last_executed_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logs.Log'),
        ),
    ]
