# Generated by Django 2.2.1 on 2019-05-24 02:17

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('scheduler', '0025_auto_20180826_1830'), ('scheduler', '0026_auto_20180826_1853'), ('scheduler', '0027_auto_20180826_1908'), ('scheduler', '0028_auto_20180827_2121'), ('scheduler', '0029_auto_20180828_1827'), ('scheduler', '0030_remove_scheduledaction_type'), ('scheduler', '0031_auto_20180829_0938'), ('scheduler', '0032_auto_20180829_0939'), ('scheduler', '0033_auto_20180829_0940'), ('scheduler', '0034_auto_20180829_0943'), ('scheduler', '0035_remove_scheduledaction_deleted')]

    dependencies = [
        ('action', '0038_auto_20180826_1505'),
        ('logs', '0006_auto_20180825_1123'),
        ('scheduler', '0024_auto_20180826_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledaction',
            name='message',
        ),
        migrations.AddField(
            model_name='scheduledaction',
            name='last_executed_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logs.Log'),
        ),
        migrations.AlterField(
            model_name='scheduledaction',
            name='payload',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True, verbose_name='payload'),
        ),
        migrations.RemoveField(
            model_name='scheduledaction',
            name='bcc_email',
        ),
        migrations.RemoveField(
            model_name='scheduledaction',
            name='cc_email',
        ),
        migrations.RemoveField(
            model_name='scheduledaction',
            name='send_confirmation',
        ),
        migrations.RemoveField(
            model_name='scheduledaction',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='scheduledaction',
            name='track_read',
        ),
        migrations.AlterField(
            model_name='scheduledaction',
            name='item_column',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_actions', to='workflow.Column', verbose_name='Column to select the elements for the action'),
        ),
        migrations.RemoveField(
            model_name='scheduledaction',
            name='type',
        ),
        migrations.AddField(
            model_name='scheduledaction',
            name='description_text',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='scheduledaction',
            name='name',
            field=models.CharField(default='Scheduled action', max_length=256, verbose_name='name'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='scheduledaction',
            unique_together={('name', 'action')},
        ),
        migrations.RemoveField(
            model_name='scheduledaction',
            name='deleted',
        ),
    ]
