# Generated by Django 2.2.3 on 2019-08-02 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_squashed_0005_auto_20190419_0738'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ontaskuser',
            table='ontask_user',
        ),
    ]
